/*************************************************
 ** DatabaseInterface.cpp
 ** Class to interface with sqlite3.
 ** Written: S.V. Paulauskas - 30 Aug 2011
 ************************************************/
#include <iostream>

#include <cstdlib>

#include "DatabaseInterface.h"

using std::cout;
using std::endl;

//********** DatabaseInterface **********
DatabaseInterface::DatabaseInterface(const std::string &databaseName)
{
   int returnCode = sqlite3_open_v2(databaseName.c_str(), &database, 
				    SQLITE_OPEN_READWRITE,"unix");
   
   if(returnCode) {
      cout << "Cannot open database named " << databaseName << endl
	   << "Sqlite3 error message: " << sqlite3_errmsg(database) << endl;
      sqlite3_close(database);
      exit(1);
   } else {
      cout << "Successfully opened database: " << databaseName << endl;
   }
   
}


//********** DatabaseInterface **********
DatabaseInterface::DatabaseInterface(const int &noArgs)
{
   if(noArgs < 3) {
      OutputHelpInfo();
      exit(1);
   }   
}


//********** ~DatabaseInterface() **********
DatabaseInterface::~DatabaseInterface()
{
   sqlite3_close(database);
}


//********** OutputHelpInfo **********
void DatabaseInterface::OutputHelpInfo(void)
{
   cout << endl << "A program to help organize gammas." << endl
	<< "Example: ./gammaSearch <database name> <flag> <gammaEnergy>" << endl
	<< "Recognized flags (place before the energy): " << endl
	<< "-h -> displays this message" << endl
	<< "-g -> outputs general information (default)" << endl
	<< "-c -> outputs general + coincidence information" << endl
	<< "-f -> outputs general + fit information" << endl
	<< "-v -> outputs all information" << endl 
	<< "-e -> Enters edit mode for editing the database." << endl
	<< "To search in an energy range simply enter the " 
	<< "low and high bound." << endl
	<< "General output for a range can be generated by passing" 
	<< " the \"-g\" flag." << endl
	<< "Problems? Contact stanpaulauskas@gmail.com" << endl << endl;
}
