#!/bin/bash

#for file in *.dat
#do
#    name=$(basename $file .dat)
#    sed s/\"/\'/g $file > $name-db.dat
#done

#awk 'NR>1 {printf "%s,%s,\x27%s\x27,%s,", $1, $2, $3, $4 ; for(i=5;i<=NF;i++){printf "%s ", $i}; printf "\n"}' generalInfo-db.dat > generalInfo-awked.dat

#awk 'NR>1 {for(i=1;i<=9;i++){printf "%s,", $i}; for(i=10;i<=NF;i++){printf "%s ", $i}; printf "\n"}' fitInfo-db.dat > fitInfo-awked.dat

#awk 'NR>1 && NR%2==0{for(i=1;i<=8;i++){printf "%s,", $i}; for(i=10;i<=NF;i++){printf "%s ", $i}; printf "\n"}' coincidenceInfo-db.dat > coincidenceInfo-awked.dat

#while read line
#do
#    ./database 73cu.db "insert into coinInfo values($line)"
#done < coincidenceInfo-awked.dat